name: Deploy Infrastructure with Ansible

on:
  push:
    branches: [ "ansible" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Run ansible deployment
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y ansible sshpass

      - name: Create vault password file
        run: echo "${{ secrets.VAULT_PASS }}" > vault_pass.txt

      - name: Run base playbook (system setup)
        run: ansible-playbook -i inventory.ini playbooks/base.yml --vault-password-file vault_pass.txt

      - name: Run docker setup
        run: ansible-playbook -i inventory.ini playbooks/docker.yml --vault-password-file vault_pass.txt

      - name: Run database setup
        run: ansible-playbook -i inventory.ini playbooks/db.yml --vault-password-file vault_pass.txt

      - name: Run CMS setup
        run: ansible-playbook -i inventory.ini playbooks/cms.yml --vault-password-file vault_pass.txt
