name: Deploy Infrastructure via Ansible

on:
  push:
    branches:
      - ansible
  workflow_dispatch:

jobs:
  deploy:
    name: Run ansible deployment
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare vault password file
        env:
            VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: |
          echo "$VAULT_PASS" > .vault_pass.txt
          chmod 600 .vault_pass.txt

      - name: verify ansible.cfg is correct
        run: |
            cd ansible
            echo "Using ansible.cfg:"
            cat ansible.cfg

      - name: prepare secrets
        run: |
          cd ansible
          mkdir secrets

      - name: Create vault secrets file from GitHub Secret
        env:
          VAULT_SECRETS: ${{ secrets.VAULT_SECRETS }}
        run: |
          cd ansible
          echo "$VAULT_SECRETS" > secrets/vault_secrets.yml
          ansible-vault encrypt secrets/vault_secrets.yml

      - name: Create vault users file from GitHub Secret
        env:
          VAULT_SECRETS: ${{ secrets.VAULT_USERS_DATA }}
        run: |
          cd ansible
          echo "$VAULT_USERS_DATA" > secrets/vault_users.yml
          ansible-vault encrypt secrets/vault_users.yml

      - name: Create data base vault file from GitHub Secret
        env:
          VAULT_SECRETS: ${{ secrets.DB_SECRETS }}
        run: |
          cd ansible
          echo "$DB_SECRETS" > secrets/db_secrets.yml
          ansible-vault encrypt secrets/db_secrets.yml

      - name: Run Ansible playbooks
        run: |
          cd ansible
          # Разворачиваем базовую систему
          ansible-playbook playbooks/base-setup.yml
          # Управляем пользователями
          ansible-playbook playbooks/user-management.yml
          # Настраиваем Docker
          ansible-playbook playbooks/docker-setup.yml

      - name: Cleanup vault pass file
        run: rm -f ansible/.vault_pass.txt

#      - name: Deploy Base & Docker Setup
#        run: |
#          ansible-playbook -i inventory.ini playbooks/base.yml \
#            --vault-password-file .vault_pass.txt \
#            -e "ansible_user=${{ env.TARGET_USER }} ansible_host=${{ env.TARGET_HOST }}"

#          ansible-playbook -i inventory.ini playbooks/docker.yml \
#            --vault-password-file .vault_pass.txt \
#            -e "ansible_user=${{ env.TARGET_USER }} ansible_host=${{ env.TARGET_HOST }}"

#      - name: Deploy DB Setup
#        run: |
#          ansible-playbook -i inventory.ini playbooks/db.yml \
#            --vault-password-file .vault_pass.txt \
#            -e "ansible_user=${{ env.TARGET_USER }} ansible_host=${{ env.TARGET_HOST }}"

#      - name: Deploy CMS Setup
#        run: |
#          ansible-playbook -i inventory.ini playbooks/cms.yml \
#            --vault-password-file .vault_pass.txt \
#            -e "ansible_user=${{ env.TARGET_USER }} ansible_host=${{ env.TARGET_HOST }}"
